spring:
  application:
    name: catalog

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    contexts: dev

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

debug: true

server:
  port: 8081

kafka:
  topics:
    product: product-events
    order-commands: order-commands
    catalog-replies: catalog-replies